# -*- coding: utf-8 -*-s
# Generated by Django 1.10rc1 on 2016-08-03 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_emp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='user',
        ),
    ]
